# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tree of Life
email: ''
description: > # this means to ignore newlines until "baseurl:"
  Tree of Life Birth and Gynecology offers home birth and birth center deliveries. 
  Our dedication and commitment to natural childbirth and parenting is what motivated us to pursue opening this center.  
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site
#twitter_username: fgauna12
#github_username:  fgauna12

# Build settings
markdown: kramdown
